name: Assign PR

on:
  pull_request_target:
    types: [opened, ready_for_review, unassigned]

permissions:
  contents: read
  pull-requests: write

jobs:
  assign-assignees:
    runs-on: ubuntu-latest
    steps:
      - name: Assign assignees using shared action
        uses: konflux-ci/release-service-automations/pr-assigner@development
        with:
          event-type: ${{ github.event.action }}
          pr-number: ${{ github.event.pull_request.number }}
          removed-assignee: ${{ github.event.action == 'unassigned' && github.event.assignee.login || '' }}
          github-token: ${{ secrets.PAT_TOKEN }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
